version: "3.9"
services:
    miner:
        build: .
        container_name: pastel_walletnode
        command: >
                bash -c "./pastelup install walletnode --force || true
                && ./pastelup start walletnode
                && ps -A
                "