version: "3.9"

services:
    pastelnode:
        build: .
        container_name: pastelnode
        command: >
                bash -c "./pastelup install node --force || true
                && ./pastelup start node
                && ps -A
                "